import {Storage} from '../app/storage'

export const STORAGES: Storage[] = [
  {
    id: 11,
    name: 'Nice',
    address: 'Berlin HauptStr.',
    maxSpaceCapacity: 20,
    maxWeightCapacity: 10,
    status: 1,
    packages: [
      {
        id: 10,
        name: 'phone',
        decription: 'IPhone 7',
        weight: 1,
        width: 2,
        height: 2,
        length: 2,
        imgUrl: 'aaa.aa',
        originStorageId: 1,
        destinationStorageId: 1,
        payment: 10,
        priority: 2,
        number: '12345',
        carryDuration: 10,
        ownerId: 1,
        carrierId: 1,
        tripId: 1,
      },
      {
        id: 10,
        name: 'phone',
        decription: 'IPhone 7',
        weight: 1,
        width: 2,
        height: 2,
        length: 2,
        imgUrl: 'aaa.aa',
        originStorageId: 1,
        destinationStorageId: 1,
        payment: 10,
        priority: 2,
        number: '12345',
        carryDuration: 10,
        ownerId: 1,
        carrierId: 1,
        tripId: 1,
      }
    ]
  },

  {
    id: 11,
    name: 'Black',
    address: 'Munich HauptStr.',
    maxSpaceCapacity: 20,
    maxWeightCapacity: 10,
    status: 1,
    packages: [
      {
        id: 10,
        name: 'phone',
        decription: 'IPhone 7',
        weight: 1,
        width: 2,
        height: 2,
        length: 2,
        imgUrl: 'aaa.aa',
        originStorageId: 1,
        destinationStorageId: 1,
        payment: 10,
        priority: 2,
        number: '12345',
        carryDuration: 10,
        ownerId: 1,
        carrierId: 1,
        tripId: 1,
      },
      {
        id: 10,
        name: 'phone',
        decription: 'IPhone 7',
        weight: 1,
        width: 2,
        height: 2,
        length: 2,
        imgUrl: 'aaa.aa',
        originStorageId: 1,
        destinationStorageId: 1,
        payment: 10,
        priority: 2,
        number: '12345',
        carryDuration: 10,
        ownerId: 1,
        carrierId: 1,
        tripId: 1,
      }
    ]
  }
];
